name: GCloudRunDeployment_DEV
on:
    push:
        branches:
            - 'dev'

jobs:
    deploy:
        name: Deploy to DEV environment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v1

            - name: Build Docker image
              run: |
                  docker build . --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT_DEV }}/${{ secrets.GCLOUD_APP_NAME }}

            - name: Authenticate into Google Cloud Platform
              uses: actions/gcloud/auth@master
              env:
                  GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

            - name: Configure Docker to use Google Cloud Platform
              uses: actions/gcloud/cli@master
              with:
                  args: 'auth configure-docker --quiet'

            - name: Push image to Google Cloud Container Registry
              uses: actions/gcloud/cli@master
              with:
                  entrypoint: sh
                  args: -c "docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT_DEV }}/${{ secrets.GCLOUD_APP_NAME }}"

            - name: Deploy on Cloud Run
              uses: actions/gcloud/cli@master
              with:
                  args: 'components install beta --quiet && gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT_DEV }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT_DEV }} --region europe-west3 --platform managed'
